export default {
  fetchInProcess: false,
  fetchError: false,
  createTriggerSuccess: false,
  createTriggerError: false,
  deleteTriggerSuccess: false,
  createTriggerInProcess: false,
  deleteTriggerInProcess: false,
  fetchTriggerInProcess: false,
  fetchTriggerSuccess: false,
  createTriggerTimeWindowInProcess: false,
  createTriggerTimeWindowSuccess: false,
  updateTriggerTimeWindowSuccess: false,
  updateTriggerTimeWindowInProcess: false,
  deleteTriggerTimeWindowInProcess: false,
  deleteTriggerTimeWindowSuccess: false,
  polygonData: [],
  triggerTimeWindows: [],
  polygonDataAdmin: [],
  fetchTriggerErrorAdmin: ""
}
