export default {
  user: {},
  mute: false,
  loginInProcess: false,
  loginError: false,
  registerInProcess: false,
  registerError: false,
  resetPasswordInProcess: false,
  resetPasswordError: false,
  sendInvitationInProcess: false,
  sendInvitationSuccess: false,
  sendInvitationError: '',
  getInvitationInProcess: false,
  getInvitationSuccess: false,
  getInvitationError: '',
  deleteAlertSuccess: false,
  createAlertSuccess: false,
  sendpasswordResetRequestInProcess: false,
  sendpasswordResetRequestSuccess: false,
  sendpasswordResetRequestError: '',
  getpasswordResetRequestInProcess: false,
  getpasswordResetRequestSuccess: false,
  getpasswordResetRequestError: '',
  generatedOTP: '',
  generateOTPError: '',
  generateOTPSuccess: false
}
