export const UPDATE_USER_IN_PROGRESS = 'UPDATE_USER_IN_PROGRESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const ADD_USER_IN_PROCESS = 'ADD_USER_IN_PROCESS';
export const UPDATE_USER_CAMERA_LICENSE_DATA = 'UPDATE_USER_CAMERA_LICENSE_DATA';
