export default {
  alerts: [],
  newAlerts: [],
  tags: {},
  pagination: {page_number: 1},
  fetchInProcess: false,
  fetchError: false,
  createAlertSuccess: false,
  createAlertError: false,
  deleteAlertSuccess: false,
  createAlertInProcess: false,
  deleteAlertInProcess: false,
  fetchPolygonAlertInProcess: false,
  fetchAlertSuccess: false,
  newAlertCount: 0,
  selectedFilterType: 4,
  shareAlertError: '',
  shareAlertSuccess: false,
  shareAlertInProcess: false,
  shareAlertErrorUuid: null,
  shareAlertInProcessUuid: null,
  shareAlertSuccessUuid: null,
  updateAlertTagsInProcess: false,
  updateAlertTagsInProcessUuid: null,
  updateAlertTagsError: '',
  updateAlertTagsErrorUuid: null,
  updateAlertTagsSuccess: false,
  updateAlertTagsSuccessUuid: null
}
